version: '3.8'

services:
  backend:
    build:
      context: ./oogiri-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
    volumes:
      - ./oogiri-backend:/usr/src/oogiri-backend
      - /usr/src/oogiri-backend/target

  frontend:
    build:
      context: ./oogiri-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    volumes:
      - ./oogiri-frontend:/app
      - /app/node_modules
