version: '3'

services:
  oogiri-backend:
    build: ./oogiri-backend
    volumes:
      - ./oogiri-backend:/usr/src/oogiri-backend
    ports:
      - "8080:8080"
    environment:
      - RUST_BACKTRACE=1
      - FRONTEND_URL=http://localhost:3000

  oogiri-frontend:
    build: ./oogiri-frontend
    volumes:
      - ./oogiri-frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8080

volumes:
  cargo-cache: