version: '3.8'

services:
  oogiri-frontend:
    build: ./oogiri-frontend
    volumes:
      - ./oogiri-frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8080

  oogiri-backend:
    build: ./oogiri-backend
    volumes:
      - ./oogiri-backend:/app
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=oogiri-dev-service-account.json
      - ALLOWED_ORIGIN=http://localhost:3000
